name: Publish Artifacts

on:
  release:
    types: [created]

jobs:
  build:
    name: Initialzing Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build

  publish-gpr:
    name : Publishing Packages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@fnconfig'
      - run: git config --global user.name 'amitpathlock'
      - run: git config --global user.email 'amit.kumar@pathlock.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push -u origin main
      - run: npm ci
      - run: |
          echo "@fnconfig:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - run: npm publish
      
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

