name: Publish Artifacts

on:
  release:
    types: [created]

jobs:
  build:
    name: Initialzing Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build

  publish-gpr:
    name : Publishing Packages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@fnconfig'
        # Use a marketplace action to automatically bump the version
      - name: Increment package version
        id: increment_version
        uses: '@amitpathlock/fnconfig@0.0.1' # Example action
        with:
          # The part of the version to increment (major, minor, or patch)
          default_increment: patch
      - run: npm ci
      - run: |
          echo "@fnconfig:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - run: npm publish
      
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

